// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUFCbvsiHJbu9Fu5ONriyFGu4odwHD2vc',
    appId: '1:882002381485:web:825fb01eeb252d4c5e1424',
    messagingSenderId: '882002381485',
    projectId: 'tastebudz-d9ac6',
    authDomain: 'tastebudz-d9ac6.firebaseapp.com',
    storageBucket: 'tastebudz-d9ac6.appspot.com',
    measurementId: 'G-E6CYZF3SSC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDyvYD6L6NC--wyuRnicalY0udAKFygwk',
    appId: '1:882002381485:android:6ddc1bbb3a930b1c5e1424',
    messagingSenderId: '882002381485',
    projectId: 'tastebudz-d9ac6',
    storageBucket: 'tastebudz-d9ac6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDY7c94aYkll_J_-f2xpx-SY0ElaJdpAm0',
    appId: '1:882002381485:ios:7587e80a92e4815a5e1424',
    messagingSenderId: '882002381485',
    projectId: 'tastebudz-d9ac6',
    storageBucket: 'tastebudz-d9ac6.appspot.com',
    iosClientId: '882002381485-nnpe8o40chmh1eagsjt29t25a9q8n4h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastebudz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDY7c94aYkll_J_-f2xpx-SY0ElaJdpAm0',
    appId: '1:882002381485:ios:7587e80a92e4815a5e1424',
    messagingSenderId: '882002381485',
    projectId: 'tastebudz-d9ac6',
    storageBucket: 'tastebudz-d9ac6.appspot.com',
    iosClientId: '882002381485-nnpe8o40chmh1eagsjt29t25a9q8n4h4.apps.googleusercontent.com',
    iosBundleId: 'com.example.tastebudz',
  );
}
